# Generated by Django 4.1.3 on 2022-11-24 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='custome',
            new_name='customer',
        ),
    ]
